###-Path to BNG2.pl-###
bng_command = /Users/elymiller/Library/Python/3.9/lib/python/site-packages/bionetgen/bng-mac/BNG2.pl

###-Paths to BNGL and EXP files-###
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/19.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/19.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/20.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/20.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/21.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/21.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/22.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/22.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/23.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/23.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/24.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/24.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/25.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/25.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/26.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/26.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/27.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/27.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/28.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/28.exp
model = /Users/elymiller/Desktop/Current_Research/Misc-Python-Projects/spring_2026_flu_talk/AZ_models/29.bngl : /Users/elymiller/Desktop/Current_Research/Misc-Python-Projects/spring_2026_flu_talk/AZ_data/29.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/30.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/30.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/31.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/31.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/32.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/32.exp

#model = /Users/elymiller/Desktop/Current_Research/Misc-Python-Projects/spring_2026_flu_talk/AZ_models/32.bngl : /Users/elymiller/Desktop/Current_Research/Misc-Python-Projects/spring_2026_flu_talk/AZ_data/32.exp

###-Output folder-###
#output_dir = /Users/l-biosci-posnerlab/Desktop/2025_NAU_FLU/spring_2026_flu_talk/results/Arizona
output_dir = /Users/elymiller/Desktop/Current_Research/Misc-Python-Projects/spring_2026_flu_talk/results/29_line_2


###-Algorithm-###
fit_type = de

###-Objective function-###
objfunc = neg_bin_dynamic

###-Adjustable parameters and constraints-###
#uniform_var = I0__FREE 0.001 0.1
uniform_var = b0__FREE 0.3 0.4
uniform_var = b1__FREE 0.79 0.9
uniform_var = b2__FREE 1.4 1.6
uniform_var = gamma__FREE 0.75 0.85
uniform_var = mult__FREE 4550 4700
uniform_var = r__FREE 1 4000
uniform_var = t0__FREE 0 5.0
uniform_var = t1__FREE 6.7 7.0
uniform_var = t2__FREE 11.0 12.0

###-Algorithmic specifications-###
step_size = 0.02
population_size = 20
parallel_count = 8
verbosity = 2
burn_in = 2500
adaptive = 2500
max_iterations = 50000
continue_run = 0
sample_every = 1
output_noise_trajectory = H_weekly
refine = 0
starting_params = 10.38628034588947346 0.8519094923834514 1.4187305478189347 0.8238423746802017 4587.359616916871 7.52566251598368 0.14842983310412064 6.722100440377796 11.918336062763286
