###-Path to BNG2.pl-###
bng_command = /opt/anaconda3/lib/python3.12/site-packages/bionetgen/bng-mac/BNG2.pl

###-Paths to BNGL and EXP files-###
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/19.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/19.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/20.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/20.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/21.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/21.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/22.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/22.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/23.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/23.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/24.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/24.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/25.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/25.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/26.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/26.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/27.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/27.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/28.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/28.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/29.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/29.exp
model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/30.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/30.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/31.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/31.exp
#model = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_models/32.bngl : /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/AZ_data/32.exp

#model = /Users/elymiller/Desktop/Current_Research/Misc-Python-Projects/spring_2026_flu_talk/AZ_models/32.bngl : /Users/elymiller/Desktop/Current_Research/Misc-Python-Projects/spring_2026_flu_talk/AZ_data/32.exp

###-Output folder-###
#output_dir = /Users/l-biosci-posnerlab/Desktop/2025_NAU_FLU/spring_2026_flu_talk/results/Arizona
output_dir = /Users/l-biosci-posnerlab/Desktop/spring_2026_flu_talk/results/Arizona


###-Algorithm-###
fit_type = am

###-Objective function-###
objfunc = neg_bin_dynamic

###-Adjustable parameters and constraints-###
#uniform_var = I0__FREE 0.001 0.1
uniform_var = b0__FREE 0.05 2.0
uniform_var = gamma__FREE 0.01 1.2
uniform_var = mult__FREE 1.0 9000.0
uniform_var = r__FREE 20 4000
uniform_var = t0__FREE 0 7
uniform_var = b1__FREE 0.05 2.0
uniform_var = t1__FREE 8 22

###-Algorithmic specifications-###
step_size = 0.02
population_size = 1
parallel_count = 1
verbosity = 0
burn_in = 2500
adaptive = 2500
max_iterations = 50000
continue_run = 0
sample_every = 1
output_noise_trajectory = H_weekly
refine = 0
#starting_params = 1.763853196779028853e-01 2.241776761421841457e-01 2.611363349373690653e+03 2.622392604093898626e+03 9.676573847595787425e-01 8.504247450813484654e-01 2.002715019036102007e+01
